# Options for analysis running.
run:
    concurrency: 4
    timeout: 5m
    issues-exit-code: 1
    tests: false
    go: '1.18'
linters:
    # Disable all linters.
    # Default: false
    # Enable specific linter
    # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
    enable:
#        - bodyclose 1.18
        #        - deadcode
        - depguard
        - dogsled
        - dupl
        - errcheck
        - exportloopref
        - exhaustive
        - goconst
        - gocritic
        - gofmt
        - goimports
        - gomnd
        - gocyclo
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nolintlint
        - nakedret
        - prealloc
        - predeclared
        - revive
        - staticcheck
        - stylecheck
        - thelper
#        - tparallel 1.18
        - typecheck
        - unconvert
#        - unparam 1.18
        - varcheck
        - whitespace
#        - wsl
        - gochecknoinits
        - gocognit # Computes and checks the cognitive complexity of functions
        - importas
        #        - lll # Reports long lines
        - maintidx
        - makezero
        - misspell
        - nestif
#        - wrapcheck
#        - nilerr # 1.18
    disable:
        - structcheck
        - deadcode
        - unused
